from selenium.webdriver.common.by import By

class UrbanRoutesPage:

    from_field = (By.ID, "from")
    to_field = (By.ID, "to")
    taxi_button_round = (By.XPATH, "//*[@id='root']/div/div[3]/div[3]/div[1]/div[3]/div[1]/button")
    confort_active = (By.XPATH, "//*[@id='root']/div/div[3]/div[3]/div[2]/div[1]/div[5]/div[1]/img")
    button_phone = (By.CLASS_NAME, "np-button")
    number_field = (By.XPATH, "//*[@id='phone']")
    selection_button_next = (By.XPATH, "//*[@id='root']/div/div[1]/div[2]/div[1]/form/div[2]/button")
    code_field = (By.ID, "code")
    button_accept = (By.XPATH, "//*[@id='root']/div/div[1]/div[2]/div[2]/form/div[2]/button[1]")
    methods_pay = (By.CLASS_NAME, "pp-text")
    to_add_card = (By.CLASS_NAME, "pp-plus")
    card_number_field = (By.ID, "number")
    card_code_field = (By.NAME, "code")
    botton_to_add = (By.XPATH, "//button[normalize-space()='Agregar']")
    close_button = (By.XPATH, "//*[@id='root']/div/div[2]/div[2]/div[1]/button")
    message_for_driver_field = (By.ID, "comment")
    requisitos_del_pedido_button = (By.CSS_SELECTOR, ".reqs-head")
    selecction_blanket = (By.XPATH, "//div[@class='workflow']//div[1]//div[1]//div[2]//div[1]//span[1]")
    selecction_ice = (By.XPATH, "//*[@id='root']/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[3]/div/div[2]/div[1]/div/div[2]/div/div[3]")
    smart_button_main = (By.CLASS_NAME, "smart-button")
    wait_for_driver = (By.CLASS_NAME, "order-header-title")